### ISSUE TITLE
Crashes on 10.11

### ISSUE THREAD

**Issue by snaptopixel** [bdkjones/MuzzleApp#3] opened 2017-07-06 16:10 UTC
1. Downloaded the app (thank you!), placed in Applications and launched.
1. Icon appeared in taskbar
1. Joined a hangout in Chrome as the only participant
1. Clicked screen share button
1. Task bar icon immediately disappeared and DND was NOT turned on
1. Shared my screen
1. Stopped screen sharing
1. Icon's empty space eventually went away
1. 100% reproducible

<img src="https://cl.ly/2B052c0Y2F1t/Image%202017-07-06%20at%2012.07.44%20PM.png" width="500"/>
<img src="https://cl.ly/0k100e2A2d01/Image%202017-07-06%20at%2012.08.08%20PM.png" width="500"/>
<img src="https://cl.ly/3H122B1l2Q06/Screen%20Recording%202017-07-06%20at%2012.06%20PM.gif" width="500"/>

**Comment by bdkjones** [comment] 2017-07-06 16:26
Interesting. We can't reproduce this over here and Google Hangouts is something we tested specifically.

Which version of macOS and Chrome? Which extensions are installed in Chrome? What other apps are running on your system?

**Comment by snaptopixel** [comment] 2017-07-07 02:07
Hey @bdkjones, I'll see if I can't do some more testing tomorrow, versions are shown in the screenshots ;)

**Comment by bdkjones** [comment] 2017-07-07 07:26
Ah, yea, missed the OS X screenshot. 

We didn't formally test 10.11. The APIs Muzzle uses have been around since 10.8, and we only support 10.11+, so we didn't expect any differences. I'll have to spin up a VM and see what the hell is wrong with 10.11.

**Comment by bdkjones** [comment] 2017-07-07 07:29
Could one of you open `console.app`, reproduce this crash, and see if anything is put into the log? (You'll want to clear it first and look quickly; macOS has gotten INSANELY chatty in log files.)

**Comment by bdkjones** [comment] 2017-07-07 07:34
*sigh*. I found the issue. There's a call to an API that's only available on 10.12+. I'll fix that now and ship an update.

**Comment by bdkjones** [comment] 2017-07-07 09:10
Fixed in 1.2. Check for updates and thanks.

**Closed as completed by bdkjones** 2017-07-07 09:10 UTC

**Comment by mgrn0** [comment] 2017-07-08 19:01
Works flawless now with Techmith's products, thanks!
