### ISSUE TITLE
Muzzle crashes in both Techmith Camtasia and Techsmith Snagit

### ISSUE THREAD

**Issue by mgrn0** [bdkjones/MuzzleApp#7] opened 2017-07-06 20:04 UTC
- I  downloaded the app, thanks for making this tool free (like it was in the good old osx app/tool days :)
- It took me an extra email to you to find out the tool is smart enough to recognize when the screen is shared/recorded. Shame on me. This is brilliant!
- I tried to use it with Techsmiith Camtasia (https://www.techsmith.com/video-editor.html) and Techsmith Snagit (https://www.techsmith.com/screen-capture.html) and both crash Muzzle once recording starts (the Muzzle icon is gone, and the process is vanishing from the activity monitor).
- I cannot record a video of that happening since i cannot record screen recording software, but it is 100% reproduceable.

My setup: OSX 10.11.6
Camtasia 10.0.6
Snagit4.1.5 (but since it affects both Techmith products I guess its something related to the way they record the screen).

Can I help to debug this issue?

**Comment by bdkjones** [comment] 2017-07-07 07:27
Yea, this appears to be related to OS X 10.11. There's another issue with a crash on 10.11. I'll have to spin up a VM and investigate.

**Comment by bdkjones** [comment] 2017-07-07 07:27
Dupe of #3

**Closed as completed by bdkjones** 2017-07-07 07:27 UTC
